<a href="https://colab.research.google.com/github/ZiyueLiu-zl3472/week5/blob/main/Numpy_Indexing2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
nums = np.arange(1,11)*100

idx = np.arange(10)
# create index from 0 to 9
print(idx)

print(nums[idx])

idx_rand = idx.copy()
np.random.shuffle(idx_rand)

nums[idx_rand]



[0 1 2 3 4 5 6 7 8 9]
[ 100  200  300  400  500  600  700  800  900 1000]


array([ 800,  900,  600,  500, 1000,  700,  400,  300,  200,  100])

In [6]:
mat = np.arange(1,13).reshape(3,4)
#create mat range from 1 to 12 and reshape it into 3 rows and 4 columns
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
mat[:,0]
#see everything in the 1st column

array([1, 5, 9])

In [8]:
mat[0,:]

array([1, 2, 3, 4])

In [9]:
mat[1:,2:]
#row 1 up and column 2 up

array([[ 7,  8],
       [11, 12]])

In [10]:
mat[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
mat[-1,-2]
#mat[1,2]=7 row and column both count from 0

11

In [ ]:
# Mask

In [15]:
mask = mat >=7
#numbers no less than 7

In [16]:
mat[mask]

array([ 7,  8,  9, 10, 11, 12])

In [17]:
mask


array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])