<a href="https://colab.research.google.com/github/ZiyueLiu-zl3472/week5/blob/main/Numpy_Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.arange(1,4)

In [3]:
a

array([1, 2, 3])

In [4]:
b = 1

In [5]:
a + b
#add scalar to entire array

array([2, 3, 4])

In [6]:
c = np.arange(2,5)

In [7]:
(a,c)
#create a new array

(array([1, 2, 3]), array([2, 3, 4]))

In [8]:
a+c+1
#add a and c and 1
#1 is treated as array same size of a and c with constant 1

array([4, 6, 8])