<a href="https://colab.research.google.com/github/ZiyueLiu-zl3472/week5/blob/main/Numpy_LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
mat = np.arange(100,116).reshape(4,4)
#put into 4 by 4 matrix

In [3]:
print(mat)

[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]]


In [4]:
matInv=np.linalg.inv(mat)
#get the inverse


In [5]:
matInv@mat

array([[ 0.       , -0.8125   , -0.625    , -1.4375   ],
       [ 0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.875    ,  0.8828125,  0.890625 ,  0.8984375],
       [-1.125    , -0.2421875,  0.640625 ,  0.5234375]])

In [6]:
np.linalg.eig(mat)

EigResult(eigenvalues=array([ 4.30185966e+02, -1.85966085e-01, -4.47083143e-15,  1.19197020e-14]), eigenvectors=array([[-0.47169744,  0.67598178,  0.21536006,  0.19939064],
       [-0.49027799,  0.22879235,  0.08821977, -0.64609049],
       [-0.50885854, -0.21839709, -0.82251973,  0.69400908],
       [-0.52743909, -0.66558652,  0.51893989, -0.24730922]]))

In [10]:
X = np.array([[1,2],[3,4]])#independent variable
y = np.array([5,6])#dependent variable
z=np.linalg.solve(X,y)
z@X

array([ 9.5, 10. ])

In [ ]:
X@z

array([5., 6.])

In [ ]:
mat @ mat

array([[43056, 43462, 43868, 44274],
       [44752, 45174, 45596, 46018],
       [46448, 46886, 47324, 47762],
       [48144, 48598, 49052, 49506]])

In [ ]:
mat[0]

array([100, 101, 102, 103])

In [ ]:
mat[0] @ mat

array([43056, 43462, 43868, 44274])

In [ ]:
mat @ mat[0]

array([41214, 42838, 44462, 46086])

In [ ]:
mat @ mat[0].T

array([41214, 42838, 44462, 46086])

In [ ]:
mat.T
#transpose

array([[100, 104, 108, 112],
       [101, 105, 109, 113],
       [102, 106, 110, 114],
       [103, 107, 111, 115]])

In [ ]:
mat

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115]])